version: '3'

services:
  postgres-sonar:
    image: postgres
    ports:
    - "9432:5432"
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar
    volumes:
      - ./data/postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ./data/postgresql_data:/var/lib/postgresql/data
  sonar:
    image: sonarqube
    ports:
    - "9000:9000"
    environment:
      sonar.jdbc.username: sonar
      sonar.jdbc.password: sonar
      sonar.jdbc.url: jdbc:postgresql://postgres-sonar:5432/sonar
    depends_on:
    - postgres-sonar
 #   volumes:
#      - ./data/sonarqube/conf:/opt/sonarqube/conf
#      - ./data/sonarqube/extensions:/opt/sonarqube/extensions
#      - ./data/sonarqube/logs:/opt/sonarqube/logs
#      - ./data/sonarqube/data:/opt/sonarqube/data

